version: "3.9"  # optional since v1.27.0
services:
  webapp:
    image: datascientest/fastapi:1.0.0
    container_name: fastapi
    networks:
       api_network:
          ipv4_address: 172.28.1.1
    ports:
       - "8000:8000"
    
  test_authentication:
    image: test_authentication:latest
    volumes:
      - /home/ubuntu/docker_pratique/:/test_authentication 
    container_name: test_authentication
    networks:
       api_network:
           ipv4_address: 172.28.1.2
    build:
      context: .
      dockerfile: Dockerfile_authentication
    environment:
      LOG: "1"

  test_authorization:
    image: test_authorization:latest
    volumes:
      - /home/ubuntu/docker_pratique/:/test_authorization
    container_name: test_authorization
    networks:
      api_network:
          ipv4_address: 172.28.1.3
    build:
      context: .
      dockerfile: Dockerfile_authorization
    environment:
       LOG: "1"
    
  test_content:
    image: test_content:latest
    volumes:
      - /home/ubuntu/docker_pratique/:/test_content
    container_name: test_content
    networks:
      api_network:
         ipv4_address: 172.28.1.4

    build:
      context: .
      dockerfile: Dockerfile_content
    environment:
      LOG: "1" 
      
networks:
   api_network:
      ipam:
         driver: default
         config:
            - subnet: 172.28.0.0/16
            
